### ISSUE TITLE
Failure to build iOS release bundle.

### ISSUE THREAD

**Issue by Kasendwa** [MatiFace/react-native-mati-global-id-sdk#3]
Hello,

When I try to build a release version of the iOS app, I run into the following error

`bitcode bundle could not be generated because '/Users/{....}/ios/Pods/Mati-Global-ID-SDK/MatiGlobalIDSDK.framework/MatiGlobalIDSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/{...}/ios/Pods/Mati-Global-ID-SDK/MatiGlobalIDSDK.framework/MatiGlobalIDSDK' for architecture armv7`

The following is my system configuration

> System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 64.75 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.14 - /anaconda2/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by aposnovmati** [comment]
@Kasendwa Hello, issue is still actual?

**Comment by Kasendwa** [comment]
Hi @aposnovmati, this was fixed in one of those builds that came after.
