### ISSUE TITLE
MatiLoginButton just shows spinner forever

### ISSUE THREAD

**Issue by rmacqueen** [MatiFace/react-native-mati-global-id-sdk#7]
The `<MatiLoginButton />` component just shows a spinner forever when its rendered, and is not clickable. I'm on the latest version of this package and did a `pod install` before running.
<img width="323" alt="Screen Shot 2020-09-30 at 3 34 08 PM" src="https://user-images.githubusercontent.com/1205705/94732302-f9a34200-035d-11eb-990c-d0fbb8ce5ed2.png">

**Comment by aposnovmati** [comment]
@rmacqueen Hello, what exactly version do you using?
1) of this plugin
2) ios sdk by cocoapods

**Comment by rmacqueen** [comment]
@aposnovmati I am using the latest version (1.1.0) of this plugin

and here is the full print out of `react-native info`:

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.30 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.0 - ~/.nvm/versions/node/v10.20.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by rmacqueen** [comment]
I'm getting the same issue even with the 'example' app included in this repo

**Comment by aposnovmati** [comment]
@rmacqueen When you start "pod install" in ios dir, what exactly version of  Mati-Global-ID-SDK do you see?

**Comment by rmacqueen** [comment]
I get `Installing Mati-Global-ID-SDK (2.8.1)`

This is on the example app too

**Comment by aposnovmati** [comment]
Yes, it right last version, is it issue is actual?  If yes, could you please share some logs or code examples to my email andrey.posnov@mati.io ?

**Comment by rmacqueen** [comment]
I couldn't see any logs in either the react debugger or in native iOS. Does mati emit logs? Are you also getting it on the example app in this repo?

**Comment by aposnovmati** [comment]
@rmacqueen unfortunately I can not reproduce your bug, give me 1 day, I'll try to see what can be done, in any case, write me an email, suddenly i need some kind of yours private data, clientid or something

**Comment by aposnovmati** [comment]
@rmacqueen We checked everything again, everything works fine, updated the sample application, please try to look at it again.

**Comment by rmacqueen** [comment]
Thanks, it works now!
