### ISSUE TITLE
setBorderRadius already defined in MatiLoginButtonManager

### ISSUE THREAD

**Issue by AgustinCarabajal** [MatiFace/react-native-mati-global-id-sdk#8]
I got this error from the last commit when I'm trying to build the app

<img width="836" alt="Captura de Pantalla 2020-09-30 a la(s) 20 09 56" src="https://user-images.githubusercontent.com/22131218/94835316-eb016d00-03e7-11eb-886f-2965d41ce8bb.png">

**Comment by AgustinCarabajal** [comment]
@aposnovmati Are there any updates on this matter?

**Comment by ericfumarola** [comment]
Hello guys! I'm having the same issue. Is there any workaround or near fix? Thanks!

**Comment by aposnovmati** [comment]
@ericfumarola @AgustinCarabajal Hello, if you need to specify flowid, please wait one more day and we release a fix with version 1.1.1, if you don't need to specify flowid, you can use version 1.0.0, it should works well

**Comment by aposnovmati** [comment]
@ericfumarola @AgustinCarabajal Hello, sorry for waiting, we were updated the plugin to 1.2.0 where fix this problem, thank you for patience.

**Comment by AgustinCarabajal** [comment]
@aposnovmati Thanks! Now it works great.
